server:
    port: 8000

spring:
    datasource:
        url: jdbc:mysql://192.168.0.106:3306/tmp_db?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: tmp_db
        password: tmp_db
        driverClassName: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: top.linhuarui.spring.entity
    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
